/* auto-generated by NAPI-RS */
/* eslint-disable */
/* Custom public types referenced by NAPI-generated declarations. */
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue }

export interface ExecutionOptions {
  control?: QueryControl
  maxRows?: number
  maxBytes?: number
}

export interface ResultStream {
  [Symbol.asyncIterator](): AsyncIterator<JsonValue>
}

/** Exact native coordinates are decimal strings, including IDs, epochs and HLC timestamps. */
export interface JsChangeEvent {
  entity_id: string; entity_type: string; kind: string;
  epoch: string; timestamp: string; graph_incarnation: string | null;
  lpg_graph: string[] | null; triple_graph: string | null;
  before: Record<string, JsonValue> | null; after: Record<string, JsonValue> | null;
  labels: string[] | null; edge_type: string | null;
  src_id: string | null; dst_id: string | null;
  triple_subject: string | null; triple_predicate: string | null; triple_object: string | null;
}

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** Your connection to a Grafeo database. */
export declare class GrafeoDB {
  /**
   * Create a database. Pass a path for persistence, or omit for in-memory.
   * `graphModel` is `"lpg"`, `"rdf"`, or `"both"`.
   */
  static create(path?: string | undefined | null, graphModel?: 'lpg' | 'rdf' | 'both'): GrafeoDB
  /** Graph model this database was created with: `"lpg"`, `"rdf"`, or `"both"`. */
  graphModel(): 'lpg' | 'rdf' | 'both'
  /** Open an existing database at the given path. */
  static open(path: string): GrafeoDB
  /**
   * Open an existing database in read-only mode.
   *
   * Uses a shared file lock, so multiple processes can read the same
   * .grafeo file concurrently. Mutations will throw an error.
   */
  static openReadOnly(path: string): GrafeoDB
  /** Execute a GQL query with optional cancellation and output limits. */
  execute(query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<QueryResult>
  /**
   * Begin a transaction with an optional isolation level.
   *
   * Isolation levels: "read_committed", "snapshot" (default), "serializable".
   */
  beginTransaction(isolationLevel?: string | undefined | null): Transaction
  /** Returns the Grafeo engine version string. */
  version(): string
  /**
   * Clear all cached query plans.
   *
   * Forces re-parsing and re-optimization on next execution.
   * Called automatically after DDL operations, but can be invoked manually.
   */
  clearPlanCache(): void
  /**
   * Forces a WAL checkpoint.
   *
   * Flushes all pending WAL records to the main storage.
   */
  walCheckpoint(): void
  /** Close the database. */
  close(): void
  /**
   * Sets the current schema for subsequent `execute()` calls.
   *
   * Equivalent to running `SESSION SET SCHEMA <name>` but persists across
   * calls. Use `resetSchema()` to clear it.
   */
  setSchema(name: string): void
  /**
   * Clears the current schema context.
   *
   * Subsequent `execute()` calls will use the default (no-schema) namespace.
   */
  resetSchema(): void
  /** Returns the current schema name, or `null` if no schema is set. */
  currentSchema(): string | null
  /**
   * Creates a named graph projection. Returns `true` if created, `false`
   * if a projection with that name already exists.
   *
   * A projection is a read-only, filtered view of the default graph.
   * Only nodes with matching labels and edges with matching types are visible.
   */
  createProjection(name: string, nodeLabels?: Array<string> | undefined | null, edgeTypes?: Array<string> | undefined | null): boolean
  /** Drops a named graph projection. Returns `true` if it existed. */
  dropProjection(name: string): boolean
  /** Returns the names of all graph projections. */
  listProjections(): Array<string>
  /**
   * Create an index and return its committed owner ID.
   * Graph paths are component arrays, never slash-delimited strings.
   */
  createIndex(request: CreateIndexRequest): Promise<number>
  /** Drop an owner; false means only that the owner was absent. */
  dropIndex(owner: number): Promise<boolean>
  /** Atomically rebuild an existing owner, preserving its ID and configuration. */
  rebuildIndex(owner: number): Promise<void>
  /** Create a node with labels and optional properties. */
  createNode(labels: Array<string>, properties?: object | undefined | null): JsNode
  /** Create an edge between two nodes. */
  createEdge(sourceId: number, targetId: number, edgeType: string, properties?: object | undefined | null): JsEdge
  /** Get a node by ID. */
  getNode(id: number): JsNode | null
  /** Get an edge by ID. */
  getEdge(id: number): JsEdge | null
  /** Delete a node by ID. Returns true if the node existed. */
  deleteNode(id: number): boolean
  /** Delete an edge by ID. Returns true if the edge existed. */
  deleteEdge(id: number): boolean
  /**
   * Set a property on a node.
   * Throws if the node is missing or the write is rejected.
   */
  setNodeProperty(id: number, key: string, value: unknown): void
  /**
   * Set a property on an edge.
   * Throws if the edge is missing or the write is rejected.
   */
  setEdgeProperty(id: number, key: string, value: unknown): void
  /** Get the number of nodes. */
  nodeCount(): number
  /** Get the number of edges. */
  edgeCount(): number
  /** Bulk-insert nodes with vector properties. */
  batchCreateNodes(label: string, property: string, vectors: Array<Array<number>>): Promise<Array<number>>
  /** Remove a property from a node. Returns true if the property existed. */
  removeNodeProperty(id: number, key: string): boolean
  /** Remove a property from an edge. Returns true if the property existed. */
  removeEdgeProperty(id: number, key: string): boolean
  /** Add a label to an existing node. Returns true if the label was added. */
  addNodeLabel(id: number, label: string): boolean
  /** Remove a label from a node. Returns true if the label was removed. */
  removeNodeLabel(id: number, label: string): boolean
  /** Get all labels for a node. Returns null if the node doesn't exist. */
  getNodeLabels(id: number): Array<string> | null
  /** Returns high-level database information as a JSON object. */
  info(): any
  /** Returns schema information (labels, edge types, property keys) as a JSON object. */
  schema(): any
  /**
   * Saves the database to a file path.
   *
   * If in-memory, creates a new persistent database at the given path.
   * If file-backed, creates a copy at the new path.
   * The original database remains unchanged.
   */
  save(path: string): void
  /** Create a full backup of the database. */
  backupFull(backupDir: string): void
  /** Create an incremental backup (WAL records since last backup). */
  backupIncremental(backupDir: string): void
  /**
   * Search for the k nearest neighbors of a query vector.
   *
   * Returns an array of [nodeId, distance] pairs sorted by distance
   * ascending (lower = more similar). The distance scale depends on
   * the metric configured at index creation.
   */
  vectorSearch(label: string, property: string, query: Array<number>, k: number, ef?: number | undefined | null, filters?: Record<string, any> | undefined | null): Promise<Array<Array<number>>>
  /** Batch search for nearest neighbors of multiple query vectors. */
  batchVectorSearch(label: string, property: string, queries: Array<Array<number>>, k: number, ef?: number | undefined | null, filters?: Record<string, any> | undefined | null): Promise<Array<Array<Array<number>>>>
  /**
   * Search for diverse nearest neighbors using Maximal Marginal Relevance (MMR).
   *
   * Returns an array of [nodeId, distance] pairs in MMR selection order.
   * The distance values match vectorSearch() for the same nodes
   * (lower = more similar). The ordering reflects relevance-diversity
   * balance, not distance sorting.
   */
  mmrSearch(label: string, property: string, query: Array<number>, k: number, fetchK?: number | undefined | null, lambdaMult?: number | undefined | null, ef?: number | undefined | null, filters?: Record<string, any> | undefined | null): Promise<Array<Array<number>>>
  /**
   * Search a text index using BM25 scoring.
   *
   * Returns an array of [nodeId, score] pairs sorted by descending
   * relevance (higher score = more relevant). BM25 scores are
   * unbounded positive floats.
   */
  textSearch(label: string, property: string, query: string, k: number): Promise<Array<Array<number>>>
  /**
   * Perform hybrid search combining text (BM25) and vector similarity.
   *
   * Requires both a text index and a vector index
   * (both created with createIndex). If either is missing, that source is silently
   * omitted from fusion.
   *
   * Returns an array of [nodeId, score] pairs sorted by fused score
   * descending (higher = more relevant). These are fusion scores,
   * NOT distances.
   */
  hybridSearch(label: string, textProperty: string, vectorProperty: string, queryText: string, k: number, queryVector?: Array<number> | undefined | null, fusion?: string | undefined | null, weights?: Array<number> | undefined | null): Promise<Array<Array<number>>>
  /**
   * Folds retained committed LPG history into a columnar base with a writable overlay.
   *
   * Call again to fold later overlay writes. Finish asynchronous operations
   * and drop live Sessions before maintenance; active transactions, closed
   * or durability-poisoned databases are rejected. Throws on failure.
   * This is not a durability checkpoint or a history-retention lease.
   */
  compact(): void
  /**
   * Whole-state as-of scrub: node frames plus edge frames at `epoch`.
   *
   * Returns `{ nodes: [...], edges: [...] }`.
   *
   * Each node frame is
   * `{ label, nodeIds, columns }` and each edge frame is
   * `{ edgeType, edgeIds, srcIds, dstIds, columns }`. Columns align to
   * the id list (`null` = property absent at `epoch`).
   *
   * `PENDING` cannot be passed as a JS number; omit `epoch` on
   * `neighborsAtEpoch` / `edgesAtEpoch` for the current snapshot, or
   * pass `currentEpoch()`. Requires `compact()`; empty frames when
   * nothing has been compacted yet.
   */
  scrubAtEpoch(epoch: number): any
  /**
   * Neighbors of `nodeId` visible at `epoch`.
   *
   * Omit `epoch` (or pass `null`) for `PENDING` — current 1-hop,
   * the derived open CSR. `direction` is `"outgoing"` (default),
   * `"incoming"`, or `"both"`.
   */
  neighborsAtEpoch(nodeId: number, epoch?: number | undefined | null, direction?: string | undefined | null): Array<number>
  /** Every edge visible at `epoch`. Omit `epoch` for current (`PENDING`). */
  edgesAtEpoch(epoch?: number | undefined | null): Array<JsEdge>
  /** Every node visible at `epoch`. Omit `epoch` for current (`PENDING`). */
  nodesAtEpoch(epoch?: number | undefined | null): Array<JsNode>
  /** Enable CDC for all future sessions. */
  enableCdc(): void
  /** Disable CDC for all future sessions. */
  disableCdc(): void
  /** Returns whether CDC is currently enabled for new sessions. */
  get isCdcEnabled(): boolean
  /** Reads bounded node history with exact decimal ID/epoch coordinates. */
  nodeHistoryAfter(nodeId: string, cursor: Buffer | undefined | null, maxEvents: number, maxBytes: number, sinceEpoch?: string | undefined | null): Promise<JsChangePage>
  /** Reads bounded edge history with exact decimal ID/epoch coordinates. */
  edgeHistoryAfter(edgeId: string, cursor: Buffer | undefined | null, maxEvents: number, maxBytes: number, sinceEpoch?: string | undefined | null): Promise<JsChangePage>
  /** Reads an owned bounded feed page. An unchanged cursor marks the end. */
  changesAfter(cursor: Buffer | undefined | null, maxEvents: number, maxBytes: number): Promise<JsChangePage>
  /** Restore a database to a specific epoch from a backup chain. */
  static restoreToEpoch(backupDir: string, epoch: number, outputPath: string): void
  /** Runs a read-only GQL query and returns an async cursor. */
  executeStream(query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<JsResultStream>
  /**
   * Insert one RDF quad. Terms are N-Triples or bare IRIs.
   * Returns the number of newly inserted quads (0 or 1).
   */
  insertRdfQuad(subject: string, predicate: string, object: string, graph?: string | undefined | null): number
  /**
   * Bulk-insert RDF quads. Each item is `[subject, predicate, object]` or
   * `[subject, predicate, object, graph]`.
   * Returns `[inserted, epoch]`, with the exact epoch as a decimal string.
   */
  insertRdfQuads(quads: Array<[string, string, string] | [string, string, string, string]>): [number, string]
  /** Exact typed-quad membership. */
  containsRdfQuad(subject: string, predicate: string, object: string, graph?: string | undefined | null): boolean
  /** Execute a Cypher query. */
  executeCypher(query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<QueryResult>
  /** Execute a SQL/PGQ query (SQL:2023 GRAPH_TABLE). */
  executeSql(query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<QueryResult>
  /** Execute a Gremlin query. */
  executeGremlin(query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<QueryResult>
  /** Execute a GraphQL query. */
  executeGraphql(query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<QueryResult>
  /** Execute a SPARQL query against the RDF triple store. */
  executeSparql(query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<QueryResult>
  /** Execute a query in a named language with the same execution owner. */
  executeLanguage(language: string, query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<QueryResult>
  /**
   * Import a CSV file as graph nodes.
   *
   * Each row becomes a node with the given label. Column headers are used
   * as property names. Returns the number of nodes created.
   */
  importCsv(path: string, options?: CsvImportOptions | undefined | null): Promise<number>
  /**
   * Import a JSON Lines file as graph nodes.
   *
   * Each line must be a valid JSON object. Object keys become property names.
   * Returns the number of nodes created.
   */
  importJsonl(path: string, options?: JsonlImportOptions | undefined | null): Promise<number>
}
export type JsGrafeoDB = GrafeoDB

/** An edge (relationship) between two nodes with a type and properties. */
export declare class JsEdge {
  /** Get the edge ID. */
  get id(): number
  /** Get the edge type (relationship type). */
  get edgeType(): string
  /** Get the source node ID. */
  get sourceId(): number
  /** Get the target node ID. */
  get targetId(): number
  /** Get a property value by key. */
  get(key: string): unknown
  /** Get all properties as a plain object. */
  properties(): object
  /** String representation. */
  toString(): string
}

/** A node in the graph with labels and properties. */
export declare class JsNode {
  /** Get the node ID. */
  get id(): number
  /** Get the node labels. */
  get labels(): Array<string>
  /** Get a property value by key. */
  get(key: string): unknown
  /** Get all properties as a plain object. */
  properties(): object
  /** Check if the node has a specific label. */
  hasLabel(label: string): boolean
  /** String representation. */
  toString(): string
}

/** Cancellation and optional deadline for a single query invocation. */
export declare class QueryControl {
  /** Creates a control whose optional deadline starts immediately. */
  constructor(timeoutMs?: number | undefined | null)
  /** Requests cancellation before or during execution. */
  cancel(): void
  /** Whether a query has consumed this control's single execution owner. */
  get consumed(): boolean
}

/** Results from a query - access rows, nodes, and edges. */
export declare class QueryResult {
  /** Get column names. */
  get columns(): Array<string>
  /** Get number of rows. */
  get length(): number
  /** Query execution time in milliseconds (if available). */
  get executionTimeMs(): number | null
  /** Number of rows scanned during execution (if available). */
  get rowsScanned(): number | null
  /** Get a single row by index as a plain object. */
  get(index: number): object
  /** Get all rows as an array of objects. */
  toArray(): Array<object>
  /** Get first column of first row (single value). */
  scalar(): unknown
  /** Get nodes found in the result. */
  nodes(): Array<JsNode>
  /** Get edges found in the result. */
  edges(): Array<JsEdge>
  /** Returns the result formatted as a Unicode table. */
  toString(): string
  /** Get all rows as an array of arrays (no column names). */
  rows(): object
  /**
   * Returns the result as Arrow IPC stream bytes (Buffer).
   *
   * Use with the `apache-arrow` npm package:
   * ```js
   * import { tableFromIPC } from 'apache-arrow';
   * const table = tableFromIPC(result.toArrowIPC());
   * ```
   */
  toArrowIPC(): Buffer
}

/** Async cursor with explicit close and per-row copied-output admission. */
export declare class ResultStream {
  /** Column names; never waits for an in-flight native pull. */
  get columns(): Array<string>
  /** Resolves to the next row object, or null at EOF; terminal errors emit once. */
  next(): Promise<JsonValue | null>
  /** Releases the native query. Repeated calls retain its cleanup resolution. */
  close(): Promise<void>
}
export type JsResultStream = ResultStream

/**
 * A database transaction with explicit commit/rollback.
 *
 * In Node.js 22+, use with `using` for automatic cleanup:
 * ```js
 * using tx = db.beginTransaction();
 * await tx.execute("INSERT (:Person {name: 'Alix'})");
 * tx.commit();
 * // auto-rollback if commit not called
 * ```
 */
export declare class Transaction {
  /** Execute a GQL query within this transaction. */
  execute(query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<QueryResult>
  /** Commit the transaction. Fails promptly while a query is queued/running. */
  commit(): number
  /** Roll back the transaction. Fails promptly while a query is queued/running. */
  rollback(): void
  /** Whether this transaction remains active (including during a query). */
  get isActive(): boolean
  /** Insert one RDF quad in this transaction. */
  insertRdfQuad(subject: string, predicate: string, object: string, graph?: string | undefined | null): number
  /**
   * Bulk-insert RDF quads. Each item is `[subject, predicate, object]` or
   * `[subject, predicate, object, graph]`.
   */
  insertRdfQuads(quads: Array<[string, string, string] | [string, string, string, string]>): number
  /** Exact typed-quad membership in this transaction. */
  containsRdfQuad(subject: string, predicate: string, object: string, graph?: string | undefined | null): boolean
  /** Create a node inside this transaction (parser-free LPG mutation). */
  createNode(labels: Array<string>): number
  /** Execute a Cypher query within this transaction. */
  executeCypher(query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<QueryResult>
  /** Execute a SQL/PGQ query (SQL:2023 GRAPH_TABLE) within this transaction. */
  executeSql(query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<QueryResult>
  /** Execute a Gremlin query within this transaction. */
  executeGremlin(query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<QueryResult>
  /** Execute a GraphQL query within this transaction. */
  executeGraphql(query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<QueryResult>
  /** Execute a SPARQL query within this transaction. */
  executeSparql(query: string, params?: any | undefined | null, options?: ExecutionOptions | undefined | null): Promise<QueryResult>
}

/** A checked graph-qualified index creation request. */
export interface CreateIndexRequest {
  /** Property to index. */
  property: string
  /** "property" (default), "btree", "text", or "vector". */
  kind?: 'property' | 'btree' | 'text' | 'vector'
  /** Graph path components; [] is root and [""] is an empty child. */
  graph?: Array<string>
  /** Optional owner name; generated names use the reserved engine namespace. */
  name?: string
  /** Required for text/vector; omitted for property/btree. */
  label?: string
  /** Text-only minimum token length; omitted defaults to 2, and 0 is valid. */
  minTokenLength?: number
  /** Vector dimensions; omitted to infer from data. */
  dimensions?: number
  /** Vector distance metric. */
  metric?: string
  /** Vector HNSW links per node. */
  m?: number
  /** Vector HNSW construction beam width. */
  efConstruction?: number
  /** Vector quantization mode. */
  quantization?: string
}

/** Options for CSV import. */
export interface CsvImportOptions {
  /** Label to assign to created nodes (default: "Row") */
  label?: string
  /** Whether the first row contains headers (default: true) */
  headers?: boolean
}

/** Owned CDC page; its cursor is an opaque canonical byte string. */
export interface JsChangePage {
  events: Array<JsChangeEvent>
  next: Buffer
}

/** Options for JSON Lines import. */
export interface JsonlImportOptions {
  /** Label to assign to created nodes (default: "Row") */
  label?: string
}

/** Returns the active SIMD instruction set for vector operations. */
export declare function simdSupport(): string

/** Returns the Grafeo version. */
export declare function version(): string
