/* auto-generated by NAPI-RS */
/* eslint-disable */
/* Custom public types referenced by NAPI-generated declarations. */
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue }

export interface ExecutionOptions {
  control?: QueryControl
  maxRows?: number
  maxBytes?: number
}

export interface ResultStream {
  [Symbol.asyncIterator](): AsyncIterator<JsonValue>
}

/** Exact native coordinates are decimal strings, including IDs, epochs and HLC timestamps. */
export interface JsChangeEvent {
  entity_id: string; entity_type: string; kind: string;
  epoch: string; timestamp: string; graph_incarnation: string | null;
  lpg_graph: string[] | null; triple_graph: string | null;
  before: Record<string, JsonValue> | null; after: Record<string, JsonValue> | null;
  labels: string[] | null; edge_type: string | null;
  src_id: string | null; dst_id: string | null;
  triple_subject: string | null; triple_predicate: string | null; triple_object: string | null;
}
