// TypeScript definitions for @grafeo-db/wasm
// These are auto-generated by wasm-pack during build.
// The declarations below are a reference for the expected API.

/**
 * Initialize the WASM module. Must be called before using any other API.
 */
export default function init(): Promise<void>;

/**
 * A Grafeo graph database instance running in WebAssembly.
 *
 * All data is held in memory within the WASM heap. For persistence,
 * use `exportSnapshot()` / `importSnapshot()` with IndexedDB or
 * the higher-level `@grafeo-db/web` package.
 */
/** Create one graph-qualified owner; vector options apply only to kind "vector". */
export interface CreateIndexRequest {
  property: string;
  kind?: "property" | "btree" | "text" | "vector";
  /** Component array: [] is root, [""] is an empty child; no slash splitting. */
  graph?: string[];
  name?: string;
  /** Required for text/vector and omitted for property/btree. */
  label?: string;
  /** Text-only minimum token length; default 2, explicit 0 is valid. Must be a nonnegative safe integer fitting the WASM size range. */
  minTokenLength?: number;
  dimensions?: number;
  metric?: string;
  m?: number;
  efConstruction?: number;
  quantization?: string;
}

export interface ExecutionOptions {
  /** Defaults: 1,000,000 eager/collection rows and 64 MiB copied output. Zero is a real limit. */
  maxRows?: number;
  maxBytes?: number;
  language?: string;
}

/** One query owner. Omit timeoutMs; deadlines currently throw GRAFEO-Q004. */
export class QueryControl {
  constructor(timeoutMs?: number);
  cancel(): void;
  readonly consumed: boolean;
  free(): void;
}

/** Bounded native read cursor. Explicit close retains terminal errors. */
export class ResultStream {
  private constructor();
  readonly columns: string[];
  next(): Record<string, unknown> | null;
  nextChunk(maxRows: number): Record<string, unknown>[] | null;
  toArray(): Record<string, unknown>[];
  close(): void;
  free(): void;
}


/** Owned JS page; next is a 97-byte exclusive cursor. No native page needs freeing. */
export interface ChangePage {
  events: ChangeEvent[];
  next: Uint8Array;
}
/** Native coordinates are exact decimal strings. */
export interface ChangeEvent {
  entity_id: string; entity_type: string; kind: string;
  epoch: string; timestamp: string; graph_incarnation: string | null;
  before: Record<string, unknown> | null; after: Record<string, unknown> | null;
  labels: string[] | null; edge_type: string | null; src_id: string | null; dst_id: string | null;
  lpg_graph: string[] | null;
  triple_graph: string | null; triple_subject: string | null;
  triple_predicate: string | null; triple_object: string | null;
}

export class Database {
  /** Requires the cdc feature (included in full). Capture applies to future sessions. */
  setCdcEnabled(enabled: boolean): void;
  isCdcEnabled(): boolean;
  /** Positive event/native-byte bounds; null/undefined starts at the retained floor. */
  changesAfter(cursor: Uint8Array | null | undefined, maxEvents: number, maxBytes: number): ChangePage;
  /** Exact decimal u64 ID and inclusive epoch, with the same page bounds. */
  nodeHistoryAfter(id: string, sinceEpoch: string, cursor: Uint8Array | null | undefined, maxEvents: number, maxBytes: number): ChangePage;
  edgeHistoryAfter(id: string, sinceEpoch: string, cursor: Uint8Array | null | undefined, maxEvents: number, maxBytes: number): ChangePage;
  /** Controls are single-use. Native errors preserve Error.code. */
  executeWithOptions(query: string, control: QueryControl, options: ExecutionOptions | undefined, params: Record<string, unknown> | undefined): Record<string, unknown>[];
  executeRawWithOptions(query: string, control: QueryControl, options: ExecutionOptions | undefined, params: Record<string, unknown> | undefined): { columns: string[]; rows: unknown[][]; executionTimeMs?: number };
  /** GQL read cursor; active explicit transactions reject. Other DB operations report busy until cursors close. */
  executeStreamWithOptions(query: string, control: QueryControl, options: ExecutionOptions | undefined, params: Record<string, unknown> | undefined): ResultStream;
  /** Create an index and return its committed unsigned 32-bit owner ID. */
  createIndex(request: CreateIndexRequest): number;
  /** Drop by owner ID; false means absent. Other failures throw. */
  dropIndex(owner: number): boolean;
  /** Atomic replacement preserving owner/configuration; a missing owner throws. */
  rebuildIndex(owner: number): void;

  /** Creates a new in-memory database. */
  constructor();

  /**
   * Executes a GQL query and returns results as an array of objects.
   *
   * Each row becomes a JavaScript object with column names as keys.
   *
   * @example
   * ```js
   * const results = db.execute("MATCH (p:Person) RETURN p.name, p.age");
   * // [{name: "Alix", age: 30}, {name: "Gus", age: 25}]
   * ```
   */
  execute(query: string): Record<string, unknown>[];

  /**
   * Executes a GQL query and returns raw columns, rows, and metadata.
   *
   * @returns `{ columns: string[], rows: unknown[][], executionTimeMs?: number }`
   */
  executeRaw(query: string): {
    columns: string[];
    rows: unknown[][];
    executionTimeMs?: number;
  };

  /** Returns the number of nodes in the database. */
  nodeCount(): number;

  /** Returns the number of edges in the database. */
  edgeCount(): number;

  /**
   * Executes a query using a specific query language.
   *
   * Supported languages: `"gql"`, `"cypher"`, `"sparql"`, `"gremlin"`, `"graphql"`.
   * Languages require their corresponding feature flag to be enabled at build time.
   *
   * @example
   * ```js
   * const results = db.executeWithLanguage("MATCH (p:Person) RETURN p.name", "cypher");
   * ```
   */
  executeWithLanguage(
    query: string,
    language: "gql" | "cypher" | "sparql" | "gremlin" | "graphql",
  ): Record<string, unknown>[];

  /**
   * Exports the database to a binary snapshot.
   *
   * Returns a `Uint8Array` that can be stored in IndexedDB, localStorage,
   * or sent over the network. Restore with `Database.importSnapshot()`.
   *
   * @example
   * ```js
   * const bytes = db.exportSnapshot();
   * ```
   */
  exportSnapshot(): Uint8Array;

  /**
   * Creates a database from a binary snapshot.
   *
   * @param data - Bytes previously produced by `exportSnapshot()`.
   *
   * @example
   * ```js
   * const db = Database.importSnapshot(bytes);
   * ```
   */
  static importSnapshot(data: Uint8Array): Database;

  /**
   * Returns schema information about the database.
   *
   * @returns An object describing labels, edge types, and property keys.
   *
   * @example
   * ```js
   * const schema = db.schema();
   * // { Lpg: { labels: [{name: "Person", count: 5}], edge_types: [...], property_keys: [...] } }
   * ```
   */
  schema(): {
    Lpg?: {
      labels: Array<{ name: string; count: number }>;
      edge_types: Array<{ name: string; count: number }>;
      property_keys: string[];
    };
    Rdf?: {
      predicates: Array<{ iri: string; count: number }>;
      named_graphs: string[];
      subject_count: number;
      object_count: number;
    };
  };

  /**
   * Batch-imports LPG (Labeled Property Graph) data from a structured object.
   *
   * Nodes are created first, then edges. Edge `source`/`target` fields are
   * zero-based indexes into the `nodes` array.
   *
   * @example
   * ```js
   * const result = db.importLpg({
   *   nodes: [
   *     { labels: ["Person"], properties: { name: "Alix", age: 30 } },
   *     { labels: ["Person"], properties: { name: "Gus", age: 25 } },
   *   ],
   *   edges: [
   *     { source: 0, target: 1, type: "KNOWS", properties: { since: 2020 } }
   *   ]
   * });
   * // { nodes: 2, edges: 1 }
   * ```
   */
  importLpg(data: {
    nodes: Array<{
      labels: string[];
      properties?: Record<string, unknown>;
    }>;
    edges?: Array<{
      source: number;
      target: number;
      type: string;
      properties?: Record<string, unknown>;
    }>;
  }): { nodes: number; edges: number };

  /**
   * Batch-imports RDF triples from a structured object.
   *
   * Subjects and predicates are IRI strings (or blank nodes prefixed `_:`).
   * Objects can be a plain string (IRI) or a structured literal.
   *
   * Requires the `rdf` feature flag.
   *
   * @example
   * ```js
   * const result = db.importRdf({
   *   triples: [
   *     { subject: "http://example.org/Alix", predicate: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", object: "http://example.org/Person" },
   *     { subject: "http://example.org/Alix", predicate: "http://example.org/name", object: { value: "Alix" } },
   *     { subject: "http://example.org/Alix", predicate: "http://example.org/age", object: { value: "30", datatype: "http://www.w3.org/2001/XMLSchema#integer" } },
   *   ]
   * });
   * // { triples: 3 }
   * ```
   */
  importRdf(data: {
    triples: Array<{
      subject: string;
      predicate: string;
      object:
        | string
        | { value: string; datatype?: string; language?: string };
    }>;
  }): { triples: number };

  /** Returns the Grafeo version. */
  static version(): string;

  /** Frees the database from WASM memory. */
  free(): void;
}
